name: Build Image Workflow

on:
  workflow_call:
    inputs:
      # https://github.com/docker/login-action
      registry:
        description: 'Server address of Docker registry. If not set then will default to Docker Hub'
        required: false
      username:
        description: 'Username used to log against the Docker registry'
        required: false
      # password:
      #   description: 'Password or personal access token used to log against the Docker registry'
      #   required: false
      logout:
        description: 'Log out from the Docker registry at the end of a job'
        default: 'true'
        required: false
      # https://github.com/docker/metadata-action
      images:
        description: 'List of Docker images to use as base name for tags'
        required: true
      flavor:
        description: 'Flavors to apply'
        required: false
      # https://github.com/docker/build-push-action
      context:
        description: "Build's context is the set of files located in the specified PATH or URL"
        required: true
      build-args:
        description: "List of build-time variables"
        required: false
      secrets:
        # https://github.com/docker/login-action
        token:
          description: "Personal access token used to log against the Docker registry"
          required: false

jobs:
  build-and-push:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ inputs.registry }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.username }}
          password: ${{ secrets.token }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ inputs.images }}
          flavor: ${{ inputs.flavor }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ inputs.context }}
          build-args: ${{ inputs.build-args }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
